export enum UserType {
  ADMIN = 'ADMIN',
  INSURANCE_ADMIN = 'INSURANCE_ADMIN',
  INSURANCE_STAFF = 'INSURANCE_STAFF',
  CORPORATE_ADMIN = 'CORPORATE_ADMIN',
  PROVIDER_ADMIN = 'PROVIDER_ADMIN',
  STAFF = 'STAFF',
  MEMBER = 'MEMBER',
  PROVIDER = 'PROVIDER'
}

export enum AdminType {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  INSURANCE_ADMIN = 'INSURANCE_ADMIN',
  CORPORATE_ADMIN = 'CORPORATE_ADMIN',
  PROVIDER_ADMIN = 'PROVIDER_ADMIN'
} 